mod_dict = {
    2: r"$\mathcal{S}$",
    3: r"$\mathcal{S}_1$",
    5: r"$\phi$",
    6: r"$\Xi$",
    7: r"$\Xi_1$",
    10: r"$\omega_1$",
    12: r"$\omega_4$",
    15: r"$\zeta$",
    16: r"$\Omega_1$",
    18: r"$\Omega_4$",
    19: r"$\Upsilon$",
    20: r"$\Phi$",
    21: r"$\mathcal{B}$",
    22: r"$\mathcal{B}_1$",
    23: r"$\mathcal{W}$",
    24: r"$\mathcal{W}_1$",
    25: r"$\mathcal{G}$",
    27: r"$\mathcal{H}$",
    33: r"$\mathcal{Q}_5$",
    36: r"$\mathcal{Y}_5$",
    37: r"$N$",
    38: r"$E$",
    39: r"$\Delta_1$",
    40: r"$\Delta_3$",
    41: r"$\Sigma$",
    42: r"$\Sigma_1$",
    43: r"$U$",
    44: r"$D$",
    45: r"$Q_1$",
    47: r"$Q_7$",
    48: r"$T_1$",
    49: r"$T_2$",
    "Q1_Q7_W": r"$(Q_1, Q_7, \mathcal{W})$",
    "Q1Q7W_spl": r"$Q_1Q_7\mathcal{W}$",
    "Varphi": r"$\phi$",
    "Varphi_massbound": r"$\phi$"
}

uv_param_dict = {
    "kS": r"$\kappa_{\mathcal{S}}$",
    "yS1f12": r"$\left(y_{\mathcal{S}_1}\right)_{12}$",
    "yS1f21": r"$\left(y_{\mathcal{S}_1}\right)_{21}$",
    "lamVarphi": r"$\lambda_{\phi}$",
    "yVarphiuf33": r"$\left(y_{\phi}^u\right)_{33}$",
    "kXi": r"$\kappa_{\Xi}$",
    "kXi1": r"$\kappa_{\Xi1}$",
    "yomega1qqf33": r"$\left(y_{\omega_1}^{qq}\right)_{33}$",
    "yomega4uuf33": r"$\left(y_{\omega_4}^{uu}\right)_{33}$",
    "yZetaqqf33": r"$\left(y_{\zeta}^{qq}\right)_{33}$",
    "yOmega1qqf33": r"$\left(y_{\Omega_1}^{qq}\right)_{33}$",
    "yOmega4f33": r"$\left(y_{\Omega_4}\right)_{33}$",
    "yUpsf33": r"$\left(y_{\Upsilon}\right)_{33}$",
    "yPhiquf33": r"$\left(y_{\Phi}^{qu}\right)_{33}$",
    "gBH": r"$g_B^\varphi$",
    "gBdf11": r"$\left(g_B^d\right)_{11}$",
    "gBef11": r"$\left(g_B^e\right)_{11}$",
    "gBef22": r"$\left(g_B^e\right)_{22}$",
    "gBef33": r"$\left(g_B^e\right)_{33}$",
    "gBqf11": r"$\left(g_B^q\right)_{11}$",
    "gBqf33": r"$\left(g_B^q\right)_{33}$",
    "gBuf11": r"$\left(g_B^u\right)_{11}$",
    "gBuf33": r"$\left(g_B^u\right)_{33}$",
    "gB1H": r"$g_{B_1}^\varphi$",
    "gWH": r"$g_{\mathcal{W}}^\varphi$",
    "gWLf11": r"$\left(g_{\mathcal{W}}^l\right)_{11}$",
    "gWLf22": r"$\left(g_{\mathcal{W}}^l\right)_{22}$",
    "gWLf33": r"$\left(g_{\mathcal{W}}^l\right)_{33}$",
    "gWqf11": r"$\left(g_{\mathcal{W}}^q\right)_{11}$",
    "gWqf33": r"$\left(g_{\mathcal{W}}^q\right)_{33}$",
    "gW1H": r"$g_{\mathcal{W}_1}^\varphi$",
    "gGdf11": r"$\left(g_{\mathcal{G}}^d\right)_{11}$",
    "gGqf33": r"$\left(g_{\mathcal{G}}^q\right)_{33}$",
    "gGuf33": r"$\left(g_{\mathcal{G}}^u\right)_{33}$",
    "gHf33": r"$\left(g_{\mathcal{H}}\right)_{33}$",
    "gQv5uqf33": r"$\left(g_{\mathcal{Q}_5}^{uq}\right)_{33}$",
    "gY5f33": r"$\left(g_{\mathcal{Y}_5}\right)_{33}$",
    "lamNef3": r"$\left(\lambda_N^e\right)_3$",
    "lamEff3": r"$\left(\lambda_E\right)_3$",
    "lamDelta1f3": r"$\left(\lambda_{\Delta_1}\right)_3$",
    "lamDelta3f3": r"$\left(\lambda_{\Delta_3}\right)_3$",
    "lamSigmaf3": r"$\left(\lambda_{\Sigma}\right)_3$",
    "lamSigma1f3": r"$\left(\lambda_{\Sigma_1}\right)_3$",
    "lamUf3": r"$\left(\lambda_{U}\right)_3$",
    "lamDff3": r"$\left(\lambda_{D}\right)_3$",
    "lamQ1uf3": r"$\left(\lambda_{\mathcal{Q}_1}^u\right)_3$",
    "lamQ7f3": r"$\left(\lambda_{\mathcal{Q}_7}\right)_3$",
    "lamT1f3": r"$\left(\lambda_{T_1}\right)_3$",
    "lamT2f3": r"$\left(\lambda_{T_2}\right)_3$",
    "gWtiH": r"$g_{\mathcal{W}}^{\varphi}$",
    "lamQ7f33": r"$\left(\lambda_{\mathcal{Q}_7}\right)_{33}$",

}

inv_param_dict = {2: {'inv1': r"$\left|\kappa_{\mathcal{S}}\right|$"},
                  3: {'inv1': r"$\left(y_{\mathcal{S}_1}\right)_{12} \left(y_{\mathcal{S}_1}\right)_{21}$"},
                  5: {'inv1': r"$\left|\lambda_{\phi}\right|$",
                      'inv2': r"$\mathrm{sgn}(\lambda_{\phi})\left(y_{\phi}^u\right)_{33}$",
                      'inv3': r"$\left|m_\phi\right|$"},
                  "Varphi_massbound": {'inv1': r"$\left|\lambda_{\phi}\right|$",
                             'inv2': r"$\mathrm{sgn}(\lambda_{\phi})\left(y_{\phi}^u\right)_{33}$",
                             'inv3': r"$m_\phi$"},
                  "Varphi": {'inv1': r"$\left|\lambda_{\phi}\right|$",
                             'inv2': r"$\mathrm{sgn}(\lambda_{\phi})\left(y_{\phi}^u\right)_{33}$",
                            },
                  6: {'inv1': r"$\left|\kappa_{\Xi}\right|$"},
                  7: {'inv1': r"$\left|\kappa_{\Xi1}\right|$"},
                  10: {'inv1': r"$\left|\left(y_{\omega_1}^{qq}\right)_{33}\right|$"},
                  12: {'inv1': r"$\left|\left(y_{\omega_4}^{uu}\right)_{33}\right|$"},
                  15: {'inv1': r"$\left|\left(y_{\zeta}^{qq}\right)_{33}\right|$"},
                  16: {'inv1': r"$\left|\left(y_{\Omega_1}^{qq}\right)_{33}\right|$"},
                  18: {'inv1': r"$\left|\left(y_{\Omega_4}\right)_{33}\right|$"},
                  19: {'inv1': r"$\left|\left(y_{\Upsilon}\right)_{33}\right|$"},
                  20: {'inv1': r"$\left|\left(y_{\Phi}^{qu}\right)_{33}\right|$"},
                  21: {'inv1': r"$\left|\left(g_B^e\right)_{11}\right|$",
                       'inv2': r"$\left|\left(g_B^e\right)_{22}\right|$",
                       'inv3': r"$\left|\left(g_B^e\right)_{33}\right|$",
                       'inv4': r"$\mathrm{sgn}(\left(g_B^e\right)_{11})g_B^\varphi$",
                       'inv5': r"$\mathrm{sgn}(g_B^\varphi) \left(g_B^\ell\right)_{11}$",
                       'inv6': r"$\mathrm{sgn}(g_B^\varphi) \left(g_B^\ell\right)_{22}$",
                       'inv7': r"$\mathrm{sgn}(g_B^\varphi) \left(g_B^\ell\right)_{33}$",
                       'inv8': r"$\mathrm{sgn}(g_B^\varphi)\left(g_B^q\right)_{33}$",
                       'inv9': r"$\mathrm{sgn}(g_B^\varphi)\left(g_B^u\right)_{33}$"},
                  22: {'inv1': r"$\left|g_B^\varphi\right|$"},
                  23: {'inv1': r"$\left|g_{\mathcal{W}}^\varphi\right|$",
                       'inv2': r"$\mathrm{sgn}(g_{\mathcal{W}}^\varphi)\left(g_{\mathcal{W}}^l\right)_{11}$",
                       'inv3': r"$\mathrm{sgn}(g_{\mathcal{W}}^\varphi)\left(g_{\mathcal{W}}^l\right)_{22}$",
                       'inv4': r"$\mathrm{sgn}(g_{\mathcal{W}}^\varphi)\left(g_{\mathcal{W}}^l\right)_{33}$",
                       'inv5': r"$\mathrm{sgn}(g_{\mathcal{W}}^\varphi)\left(g_{\mathcal{W}}^q\right)_{33}$"},
                  24: {'inv1': r"$\left|g_{\mathcal{W}_1}^\varphi\right|$"},
                  25: {'inv1': r"$\left|\left(g_{\mathcal{G}}^d\right)_{11}\right|$",
                       'inv2': r"$\mathrm{sgn}(\left(g_{\mathcal{G}}^d\right)_{11})\left(g_{\mathcal{G}}^q\right)_{33}$",
                       'inv3': r"$\mathrm{sgn}(\left(g_{\mathcal{G}}^d\right)_{11})\left(g_{\mathcal{G}}^u\right)_{33}$"},
                  27: {'inv1': r"$\left|\left(g_{\mathcal{H}}\right)_{33}\right|$"},
                  33: {'inv1': r"$\left|\left(g_{\mathcal{Q}_5}^{uq}\right)_{33}\right|$"},
                  36: {'inv1': r"$\left|\left(g_{\mathcal{Y}_5}\right)_{33}\right|$"},
                  37: {'inv1': r"$\left|\left(\lambda_N^e\right)_3\right|$"},
                  38: {'inv1': r"$\left|\left(\lambda_E\right)_3\right|$"},
                  39: {'inv1': r"$\left|\left(\lambda_{\Delta_1}\right)_3\right|$"},
                  40: {'inv1': r"$\left|\left(\lambda_{\Delta_3}\right)_3\right|$"},
                  41: {'inv1': r"$\left|\left(\lambda_{\Sigma}\right)_3\right|$"},
                  42: {'inv1': r"$\left|\left(\lambda_{\Sigma_1}\right)_3\right|$"},
                  43: {'inv1': r"$\left|\left(\lambda_{U}\right)_3\right|$"},
                  44: {'inv1': r"$\left|\left(\lambda_{D}\right)_3\right|$"},
                  45: {'inv1': r"$\left|\left(\lambda_{\mathcal{Q}_1}^u\right)_3\right|$"},
                  47: {'inv1': r"$\left|\left(\lambda_{\mathcal{Q}_7}\right)_3\right|$"},
                  48: {'inv1': r"$\left|\left(\lambda_{T_1}\right)_3\right|$"},
                  49: {'inv1': r"$\left|\left(\lambda_{T_2}\right)_3\right|$"},
                  "Q1_Q7_W": {'inv1': r"$\left|\left(g_{\mathcal{W}}^l\right)_{11}\right|$",
                              'inv2': r"$\mathrm{sgn}\left(\left(g_{\mathcal{W}}^l\right)_{11}\right)\left(g_{\mathcal{W}}^l\right)_{22}$",
                              'inv3': r"$\left|\left(g_{\mathcal{W}}^l\right)_{33}\right|$",
                              'inv4': r"$\left|\left(g_{\mathcal{W}}^q\right)_{33}\right|$",
                              'inv5': r"$\mathrm{sgn}\left(\left(g_{\mathcal{W}}^q\right)_{33}\right)g_{\mathcal{W}}^\varphi$",
                              'inv6': r"$\left|\left(\lambda_{\mathcal{Q}_1}^u\right)_3\right|$",
                              'inv7': r"$\left|\left(\lambda_{\mathcal{Q}_7}\right)_{33}\right|$"}
                  }
