package:
  name: "smefit"
  version: "0.1.0"

source:
  git_url: https://github.com/LHCfitNikhef/smefit_release


build:
  entry_points:
    - smefit = smefit.cli:base_command

requirements:
  build:
    - python>=3.8,<3.11
    - setuptools
    - rich>=11.2.0
    - matplotlib>=3.5.1
    - pyyaml>=5.3.0
    - numpy>=1.21.5
    - pandas>=1.4.1
    - mpi4py>=3.1.3
    - scipy>=1.8.0
    - click>=8.1.3
    - cma
    - seaborn>=0.11.2

  run:
    - python
    - pandoc

test:
  imports:
    - pdbpp
    - ipython
    - pytest-cov
    - pytest
    - coverage

about:
  home: https://lhcfitnikhef.github.io/smefit_release/
  license: GPL
  license_family: GPL
  summary: "Standard Model Effective Field theory fitter"
