# .github/workflows/pre-commit.yml
name: Pre-commit
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: '--all-files'
